install:
  - set QTDIR=C:\Qt\5.9.2\mingw53_32
  - set PATH=%PATH%;%QTDIR%\bin;C:\MinGW\bin
build_script:
  - qmake kakapos.pro
  - mingw32-make
  - mkdir deploy
  - move release\kakapos.exe deploy\kakapos.exe
  - cd deploy
  - windeployqt.exe kakapos.exe
deploy:
  tag: $(appveyor_repo_tag_name)
  release: kakapos-v$(appveyor_build_version)
  description: 'kakapos automatically build release'
  provider: GitHub
  auth_token:
    secure: th4K8tOQZGHLyYEkGqeBo0e/6ZevISMhhQ2ttIglHR4sU9qGfdaq+85hndRJk4QB # your encrypted token from GitHub
  artifact: deploy/
  draft: false
  prerelease: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
