
  name: project-kakapos
  version: '0.0.2' # just for humans, typically '1.2+git' or '1.3.2'
  summary: project-kakapos is an advanced text editor. # 79 char long summary
  description: |
    project-kakapos is a text editor which want to provide an amazing user experience.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots
 
  parts:
    kakapos:
      source: .
      plugin: qmake
      qt-version: qt5 
