
  name: project-kakapos
  version: '0.0.2' # just for humans, typically '1.2+git' or '1.3.2'
  summary: project-kakapos is a text editor which want to provide an amazing user experience. # 79 char long summary
  description: |
    project-kakapos is a text editor which want to provide an amazing user experience.

  grade: devel # must be 'stable' to release into candidate/stable channels
  confinement: devmode # use 'strict' once you have the right plugs and slots

  apps:
    kakapos:
      command: desktop-launch kakapos
      plugs: [network, network-manager, unity7, opengl]
 
  parts:
    qt-app:    
      source: .
      plugin: qmake
      qt-version: qt5 
      prime:  
        - -usr/share/doc  
        - -usr/include
      install: |
        echo "INSTALLATION PARTS"
